#!/bin/sh
 consul agent \
 -node $HOSTNAME \
 -bind=$(hostname -i) \
 -retry-join=server-1 \
 -retry-join=server-2 \
 -retry-join=server-3 \
 -data-dir /var/lib/consul \
 -config-dir /etc/consul.d \
 -encrypt $ENCRYPT_KEY