#!/bin/sh
 consul agent --server \
 -bootstrap-expect 3 \
 -node $HOSTNAME \
 -bind=$(hostname -i) \
 -retry-join=server-1 \
 -data-dir /var/lib/consul \
 -config-dir /etc/consul.d \
 -encrypt $ENCRYPT_KEY \
 -ui \
 -client 0.0.0.0